#Simple Certificate Generator
student_name = input("Enter the student's name: ").strip()
course_name = input("Enter the course name: ").strip()
completion_date =input("Enter the completion date: ").strip()
print("*" * 50)
print("CERTIFICATE OF COMPLETION".center(50))
print("*" * 50)
print("\n" * 1) 
print("This certifies that".center(50))
print(f"{student_name.title()}".center(50))
print("has successfully completed".center(50))
print(course_name.center(50).upper())
print(f"on {completion_date}".center(50))
print("\n" * 1)
print("*" * 50)
print("\n" * 1)
print("Thank you for your hard work!".center(50))
print("\n" * 1)
print ("*" * 50)
print("Name length (letters only):", len(student_name.replace(" ", "")))
